# Generated by Django 3.2.16 on 2023-06-07 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabinets', '0007_alter_cabinet_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cabinet',
            name='users',
            field=models.ManyToManyField(related_name='user_cabinets', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
