# Generated by Django 3.2.16 on 2023-06-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0081_document_create_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='from_cabinet',
            field=models.CharField(blank=True, default='', help_text='From Cabinet.', max_length=200, verbose_name='Cabinet'),
        ),
    ]
