COMMAND_NAME_PLATFORM_TEMPLATE = 'platform_template'

DEFAULT_PLATFORM_CLIENT_BACKEND_ARGUMENTS = {}
DEFAULT_PLATFORM_CLIENT_BACKEND_ENABLED = ()
DEFAULT_SETTINGS_MODULE = 'mayan.settings.production'
